### ISSUE TITLE
Generate triangles inside shape

### ISSUE THREAD

**Issue by cedricdelpoux** [msurguy/triangles#13]
Hi, do you think it could be possible to generate triangles inside shape respecting the shape, not only a mask over the initial triangle background ?

Thank you very much

![capture d ecran 2015-12-18 13 48 50](https://cloud.githubusercontent.com/assets/2683300/12032595/31452afa-ae1a-11e5-8f26-e96b1608114a.png)
![capture d ecran 2015-12-18 14 01 29](https://cloud.githubusercontent.com/assets/2683300/12032596/314743c6-ae1a-11e5-9bcb-4fe28380ac28.png)

**Comment by msurguy** [comment]
Hello! 

That would be very custom work to be done because there are too many ways to input a shape (svg, jpg image, etc). 

Instead you might need to take a look at tools like http://dmesh.thedofl.com/ or https://snorpey.github.io/triangulation/.
