### ISSUE TITLE
official npm package?

### ISSUE THREAD

**Issue by maruilian11** [msurguy/triangles#14]
hi, recently we want to add your lib to https://cdnjs.com, just want to confirm if this npm package
https://www.npmjs.com/package/triangles
is your official npm package?
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6897

**Comment by msurguy** [comment]
@maruilian11 I requested the owner of that NPM package to add me as an owner and I'll republish the package as soon as that's done. 

Thanks!

**Comment by JeffRegan** [comment]
I also removed myself as the owner, so you're in total control.

**Comment by maruilian11** [comment]
thank you ! @msurguy @JeffRegan
