### ISSUE TITLE
version number for `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [msurguy/triangles#15]
hi, recently we want to add your lib to https://cdnjs.com, could you please add a version number for current files? or could we regard them as v1.0.0? 
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6897

**Comment by msurguy** [comment]
@maruilian11 I've updated the package on NPM and created a new tag here as well, feel free to use 1.0.0! Thanks!

**Comment by maruilian11** [comment]
thank you very much!
