### ISSUE TITLE
Triangles not working in Firefox NaN

### ISSUE THREAD

**Issue by champloo11** [msurguy/triangles#4]
Firefox version No.: 29.0.1
Operating System: Windows 7.
Hosted: WAMP.

Issue: Many of the features are producing "NaN". Presumably do to computations on non-numbers. Just finished working in-scroll-to-light, and am too tired to get on this right now. Opening a ticket as either a request, or a reminder.

Thanks.

**Comment by pimmey** [comment]
I'm getting NaN for xPos and yPos in controls on Firefox 38.0 (Ubuntu). More specifically, `event.x` and `event.y` are undefined in `onMouseMove`.

Basically, in Firefox `mousemove event` is missing `x` and `y` properties for some reason. There are `clientX` and `clientY` though, which correspond to `x` and `y` and are a little more cross-browser as it appears.
